/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./resources/js/Components/ApplicationLogo.vue')['default']
    Checkbox: typeof import('./resources/js/Components/Checkbox.vue')['default']
    DangerButton: typeof import('./resources/js/Components/DangerButton.vue')['default']
    Dropdown: typeof import('./resources/js/Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/Components/DropdownLink.vue')['default']
    IconNav: typeof import('./resources/js/Components/Icon/Nav.vue')['default']
    Input: typeof import('./resources/js/Components/Input.vue')['default']
    InputError: typeof import('./resources/js/Components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/Components/InputLabel.vue')['default']
    LayoutAside: typeof import('./resources/js/Components/Layout/Aside.vue')['default']
    LayoutContainer: typeof import('./resources/js/Components/Layout/Container.vue')['default']
    LayoutFooter: typeof import('./resources/js/Components/Layout/Footer.vue')['default']
    LayoutHeader: typeof import('./resources/js/Components/Layout/Header.vue')['default']
    LayoutMain: typeof import('./resources/js/Components/Layout/Main.vue')['default']
    LayoutWrapper: typeof import('./resources/js/Components/Layout/Wrapper.vue')['default']
    Link: typeof import('./resources/js/Components/Link.vue')['default']
    Modal: typeof import('./resources/js/Components/Modal.vue')['default']
    NavLink: typeof import('./resources/js/Components/NavLink.vue')['default']
    PrimaryButton: typeof import('./resources/js/Components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/Components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./resources/js/Components/SecondaryButton.vue')['default']
    TestComponent: typeof import('./resources/js/Components/TestComponent.vue')['default']
    TextInput: typeof import('./resources/js/Components/TextInput.vue')['default']
    UiAlert: typeof import('./resources/js/Components/Ui/Alert.vue')['default']
    UiCard: typeof import('./resources/js/Components/Ui/Card.vue')['default']
    UiInput: typeof import('./resources/js/Components/Ui/Input.vue')['default']
    UiToggle: typeof import('./resources/js/Components/Ui/Toggle.vue')['default']
  }
}
